# Generated by Django 3.1 on 2024-07-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='images/default_profile_picture.jpg', upload_to='userprofile'),
        ),
    ]
